language: php
sudo: false
php:
    - 7.0
install:
    - composer update --prefer-source
script:
    - vendor/bin/phpunit
cache:
    directories:
        - vendor
        - $HOME/.composer/cache
branches:
    only:
        - pdic